### ISSUE TITLE
Compile error in Arduino environment

### ISSUE THREAD

**Issue by marciopamplona** [Pharap/FixedPointsArduino#6]
**Doesn't compile in Arduino 1.8.5 and Platform.io.**

**The first error message:**

/home/mpamplona/Arduino/libraries/FixedPoints/src/FixedPoints/Details.h: In static member function 'static uint8_t FixedPointsDetails::RandomHelper<unsigned char>::Random()':
/home/mpamplona/Arduino/libraries/FixedPoints/src/FixedPoints/Details.h:176:71: error: **no matching function for call to 'random()'**
   static inline uint8_t Random() { return static_cast<uint8_t>(random()); }

**Comment by Pharap** [comment]
I can't seem to replicate this problem just using Arduino IDE 1.8.5.

Do you get an error from compiling a sketch like this?:
```
void setup()
{
	while(!Serial);
	Serial.println(random());
}

void loop()
{
}
```

**Comment by marciopamplona** [comment]
The function random(**void**) doesn't exist in the arduino environment. The random function need an argument:
https://cdn.arduino.cc/reference/en/language/functions/random-numbers/random/

I'm compiling for ESP8266 in the Linux OS.

Including the <stdlib.h> doesn't make difference.

To reproduce: install a new arduino IDE, install the library from the library manager, open the example and compile.

**Comment by Pharap** [comment]
I think this is an ESP8266-specific problem.

From the looks of it ESP8266 isn't an Arduino chip either, I can't find it on the board list and it's not AVR-based.
Most Arduino boards have access to `extern long random(void);` defined in `\hardware\tools\avr\avr\include\stdlib.h`, but from the looks of it ESP8266 doesn't have this for some reason.

If the ESP8266 has a specific define that I can use to detect it and either selectively disable the random function or implement `randomSFixed` and `randomUFixed` using `RAND_MAX` then I can offer that as a fix, but that's about all I can do.

**Comment by Pharap** [comment]
I've gone over the code and added a feature to disable the random functions.

In addition to this I have made a branch that should detect when the library is being compiled for ESP8226 and respond by disabling the random functions.
I don't however have an ESP8226 to test on so I will have to ask you @marciopamplona to test this branch for me to confirm whether or not this fixes the problem:

https://github.com/Pharap/FixedPointsArduino/tree/ESP8266-Support

If that doesn't detect the ESP8266 then try the master branch and make sure to `#define FIXED_POINTS_NO_RANDOM` before you `#include <FixedPoints.h>`.

If the ESP8226-Support branch works then I'll merge it into the master branch and release a new version.
If the ESP8226-Support branch doesn't work but the master branch does then I'll add a warning in `README.md` that code for the ESP8226 needs to `#define FIXED_POINTS_NO_RANDOM`.

**Comment by Pharap** [comment]
Fixed by #11.
Fix tested by @eried with Arduino IDE 1.8.5.
